version: '3.2'
    
services:
  picview:
    image: picview:latest
    restart: always
    container_name: picview
    environment:
      - PORT=8080
      - baseurl=http://localhost:8080
      - GIN_MODE=release
    ports:
      - 65322:8080

    expose:
      - 65322
    
    volumes:
      - /home/zyx/data/picview/:/workspace/log/
      - /home/zyx/code/picview/images:/workspace/images/
    